# Train Classifiers

Now, we are ready to train our classifiers. delimitpy has several options for classifiers:
* A Random Forest Classifier trained on the bins of the multi-dimensional SFS.
* A Fully Connected Neural Network trained on the bins of the multi-dimensional SFS.
* A Convolutional Neural Network trained on 2-dimensional SFS.

In [1]:
from delimitpy import build_predictors
from delimitpy import parse_input
import os
import pickle
import numpy as np

2024-04-01 08:23:28.380507: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Read the configuration file, and provide info from building models

In [2]:
# read the configuration file
config_parser = parse_input.ModelConfigParser("../../examples/test1/config.txt")
config_values = config_parser.parse_config()

# read the labels and models from memory.
labels = np.load(os.path.join(config_values["output directory"], 'labels.npy'), allow_pickle=True)
with open(os.path.join(config_values["output directory"], 'parameterized_models.pickle'), 'rb') as f:
    parameterized_models = pickle.load(f)

# read the simulated data
mSFS = np.load(os.path.join(config_values["output directory"], 'mSFS.npy'), allow_pickle=True)
with open(os.path.join(config_values["output directory"], 'jSFS.pickle'), 'rb') as f:
    jSFS = pickle.load(f)

## Build the RF predictor 

Next, we build a Random Forest predictor using the bins of the multi-dimensional SFS as input.

In [3]:
random_forest_sfs_predictor = build_predictors.RandomForestsSFS(config_values, mSFS, labels)
random_forest_sfs_model, random_forest_sfs_cm = random_forest_sfs_predictor.build_rf_sfs()

100 100
(80, 441)
Out-of-Bag (OOB) Error: 0.48750000000000004


/usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(


Cross-validation scores: [0.1 0.2]


/usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(


Confusion Matrix:
[[1 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 2 0 0 0]
 [1 0 0 0 1 0 0 0 0]
 [2 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 1 0 0 0]
 [0 0 1 1 0 0 0 0 1]]


# Build the CNN that takes 2D SFS as input
cnn_2d_sfs_predictor = build_predictors.CnnSFS(config_values, sfs_2d, labels)
cnn_2d_sfs_model, cnn_2d_sfs_cm = cnn_2d_sfs_predictor.build_cnn_sfs()